"""Add users_substitutes table

Revision ID: 52f63191e858
Revises: d15cb0c4a276
Create Date: 2021-03-04 16:02:28.636310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f63191e858'
down_revision = 'd15cb0c4a276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_substitutes',
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('original_product_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('substitute_product_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['original_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['substitute_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'original_product_id', 'substitute_product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_substitutes')
    # ### end Alembic commands ###
